export enum UserCheckoutFlows {
    CHECKOUT_AS_NEW_PARENT = 'CHECKOUT_AS_NEW_PARENT',
    CHECKOUT_AS_EXISTING_PARENT = 'CHECKOUT_AS_EXISTING_PARENT',
    RENEW_STUDENT_PROGRAM = 'RENEW_STUDENT_PROGRAM',
    CANCEL_STUDENT_PROGRAM = 'CANCEL_STUDENT_PROGRAM',
    ADD_SERVICE = 'ADD_SERVICE',
    SELECT_SUBJECTS = 'SELECT_SUBJECTS',
    CHANGE_SUBJECTS = 'CHANGE_SUBJECTS',
    NON_SENIOR_REGISTRATION_FLOW = 'NON_SENIOR_REGISTRATION_FLOW',
    SENIOR_REGISTRATION_FLOW = 'SENIOR_REGISTRATION_FLOW',
    CONTINUE_REGISTRATION_FLOW = 'CONTINUE_REGISTRATION_FLOW',
  }